name: MyPy Type Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Install Pixi
      uses: prefix-dev/setup-pixi@v0.5.0
      with:
        pixi-version: latest # Or specify a version
    - name: Install dependencies with UV (via Pixi)
      run: pixi install # Pixi can be configured to use UV
    - name: Run MyPy
      run: pixi run test